declare const _default: ({
    type: string;
    input: boolean;
    dataSrc: string;
    data: {
        url: string;
    };
    searchField: string;
    template: string;
    valueProperty: string;
    authenticate: boolean;
    label: string;
    key: string;
    weight: number;
    lazyLoad: boolean;
    tooltip: string;
    validate: {
        required: boolean;
    };
    inputType?: undefined;
    defaultValue?: undefined;
    clearOnHide?: undefined;
    errorLabel?: undefined;
    customConditional?: undefined;
} | {
    label: string;
    inputType: string;
    defaultValue: boolean;
    clearOnHide: boolean;
    errorLabel: string;
    key: string;
    type: string;
    tooltip: string;
    input: boolean;
    customConditional({ instance, data }: {
        instance: any;
        data: any;
    }): any;
    dataSrc?: undefined;
    data?: undefined;
    searchField?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    authenticate?: undefined;
    weight?: undefined;
    lazyLoad?: undefined;
    validate?: undefined;
} | {
    type: string;
    input: boolean;
    dataSrc: string;
    data: {
        url: string;
    };
    searchField: string;
    template: string;
    valueProperty: string;
    authenticate: boolean;
    label: string;
    key: string;
    weight: number;
    lazyLoad: boolean;
    tooltip: string;
    customConditional: string;
    validate?: undefined;
    inputType?: undefined;
    defaultValue?: undefined;
    clearOnHide?: undefined;
    errorLabel?: undefined;
} | {
    type: string;
    input: boolean;
    weight: number;
    key: string;
    label: string;
    tooltip: string;
    dataSrc?: undefined;
    data?: undefined;
    searchField?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    authenticate?: undefined;
    lazyLoad?: undefined;
    validate?: undefined;
    inputType?: undefined;
    defaultValue?: undefined;
    clearOnHide?: undefined;
    errorLabel?: undefined;
    customConditional?: undefined;
})[];
export default _default;
